-- ==============================================================================
-- 02-oracle-schema.sql
-- Base DDL Schema for Oracle Database 23c Free
-- ==============================================================================

-- 1. Departments & Employees
BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE departments (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name VARCHAR2(100) NOT NULL,
        budget NUMBER(12, 2) DEFAULT 0.00
    )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE employees (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name VARCHAR2(100) NOT NULL,
        department_id NUMBER REFERENCES departments(id),
        manager_id NUMBER REFERENCES employees(id),
        salary NUMBER(10, 2) NOT NULL,
        hire_date DATE NOT NULL,
        status VARCHAR2(20) DEFAULT ''ACTIVE''
    )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- 2. Audit Error Log Table for PRAGMA AUTONOMOUS_TRANSACTION
BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE error_audit_log (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        error_code NUMBER,
        error_message VARCHAR2(4000),
        error_backtrace VARCHAR2(4000),
        logged_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        logged_by VARCHAR2(50) DEFAULT USER
    )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- 3. Staging and Processing table for BULK COLLECT / FORALL tests
BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE salary_adjustments_stage (
        employee_id NUMBER,
        bonus_amount NUMBER(10, 2),
        processed_flag CHAR(1) DEFAULT ''N''
    )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

